### ISSUE TITLE
test_tensor_backward issue

### ISSUE THREAD

**Issue by s1Sharp** [nikita-savelyevv/ennf#1]
in module nn_lib\tests\test_tensor_backward.py: 
**function
   def test_exponent_gradient_scalar_2(self):**
        a = Tensor(3.1, requires_grad=True)
        b = F.exp(a)
        b.backward(Tensor(4))
        self.assertAlmostEqual(a.grad.data, 4*np.exp(3.1), 5)
        self.assertEqual(b.grad.data, 4)
in first assert give "not equal" output:

> raise self.failureException(msg)
> AssertionError: array(88.79179, dtype=float32) != 88.79180512576654 within 5 places (1.893191888768797e-05 difference)

i think issue with float types of default python float values and numpy float32. Default float type is float == float64 in numpy. But when we create Tensor instance, we use float32 type of numpy.
![image](https://user-images.githubusercontent.com/44301838/157355264-e111e0ce-c538-4f2b-b8e3-17260a7c8e0a.png)

if we use float64 type in assertion, when we use float32 in Tensor not correct. 

My solve this problem is change 
row:
       self.assertAlmostEqual(a.grad.data, 4*np.exp(3.1), 5)
to
       self.assertAlmostEqual(a.grad.data, np.dot(4, np.exp(np.array(3.1, np.float32))), 5)
and test complete successfully!
![image](https://user-images.githubusercontent.com/44301838/157356232-6ef392cf-f3e5-4a38-aca4-9d3f31c7d41c.png)

**Comment by nikita-savelyevv** [comment]
Thanks! Should pass now (2fad110f0e0b5f2aca3263eb5fe97474d90ccc60)

**Comment by s1Sharp** [comment]
![image](https://user-images.githubusercontent.com/44301838/157796113-29181781-c920-4ac9-ad71-106a2074279c.png)
Done success!
